#pragma config(Sensor, S1,     button1,        sensorEV3_Touch)
#pragma config(Sensor, S4,     button4,        sensorEV3_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while(getMotorEncoder(motorB) <1800)
	{
		motor[motorB] = 100;
		motor[motorC] = 100;
	}


		motor[motorB] = 0;
		motor[motorC] = 0;
		wait1Msec(5000);
		motor[motorB] = -50;
		motor[motorC] = 50;
		wait1Msec(800);
		motor[motorB] = 100;
		motor[motorC] = 100;
		wait1Msec(5000);





}
