#pragma config(Sensor, S1,     button1,        sensorEV3_Touch)
#pragma config(Sensor, S4,     button4,        sensorEV3_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(SensorValue(button1) == 1)
	{
		motor(motorB) = 100;
	}



}
