#pragma config(Sensor, S1,     button1,        sensorEV3_Touch)
#pragma config(Sensor, S4,     button4,        sensorEV3_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		while(SensorValue(button1)==0)
		{
			motor(motorC) = 100;
			motor(motorB) = 100;
		}
		motor(motorC) = -50;
		motor(motorB) = -50;
		wait1Msec(900);
		motor(motorC) = -50;
		motor(motorB) = 50;
		wait1Msec(800);



	}



}
