#pragma config(Sensor, S1,     Button1,        sensorEV3_Touch)
#pragma config(Sensor, S4,     Button4,        sensorEV3_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	// creating  a variable
	int Bspeed = 10 ;
	int Cspeed = -10;
	int mode = 1;

	while(true)
	{
		if(mode==1)
		{
			motor[motorB] = Bspeed;
			motor[motorC] = Cspeed;
			wait1Msec(5000);
			// updating the varible
			Bspeed = Bspeed +10;
			Cspeed = Cspeed + 10;
			// updating the varible
			Bspeed = Bspeed +10;
			Cspeed = Cspeed + 10;

		}

		if(SensorValue(Button1) == 1)
		{
			motor[motorC] = -50;
			motor[motorB] = -50;
			wait1Msec(200);

			motor[motorB] = 50;
			motor[motorC] = 0;
			wait1Msec(200);
			mode = 2;
		}
		if(SensorValue(Button4) == 1)
		{
			motor[motorC] = -50;
			motor[motorB] = -50;
			wait1Msec(200);

			motor[motorB] = 0;
			motor[motorC] = 50;
			wait1Msec(300);
			mode = 3;
		}
		if(mode == 3)
		{
			motor[motorB] = 95;
			motor[motorC] = 100;

		}
	}


}
